#!/bin/bash

#exec R CMD BATCH "--no-save --args $*" src/pwm.R

if [ "$#" == "0" ]
then
    # By default, echo 'Rout' output to /dev/null.
    exec R CMD BATCH --no-save src/pwm.R /dev/null
elif [ "$#" == "1" ]
then
    # If an alternative output source is provided, use it.
    exec R CMD BATCH --no-save src/pwm.R $1
else
    echo "Invalid number of arguments provided to $0: $# ($*)."
fi
